name: Security Scan CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run ESLint (SAST)
        run: npm run lint

      - name: Run npm audit (SAST)
        run: |
          npm audit --audit-level=high
        continue-on-error: true  # Continue even if vulnerabilities found

      - name: OWASP Dependency Check (SCA)
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'secure-rest-api'
          path: '.'
          format: 'HTML'
          out: 'reports'
          args: >
            --failOnCVSS 8
            --enableRetired
        env:
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dependency-check-report
          path: reports/
          retention-days: 30

      - name: Run safety checks (if vulnerabilities critical)
        if: failure()
        run: |
          echo "Security vulnerabilities detected!"
          echo "Please check the reports and fix the issues."
          exit 1